#-------------------------------------------------------------------------------
#   Contenuto del file configtx.yaml
#-------------------------------------------------------------------------------
---
################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:
    EurasiaOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            VotingConsortium:
                Organizations:
                    - *Stato
                    - *Repubblicani
                    - *Monarchici
    SignatureChannel:
        Consortium: VotingConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Stato
    VoteChannel:
        Consortium: VotingConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Stato
                - *Repubblicani
                - *Monarchici

################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        # ID to load the MSP definition as
        ID: OrdererMSP
        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: crypto-config/ordererOrganizations/eurasia.com/msp

    - &Stato
        Name: Stato
        # ID to load the MSP definition as
        ID: StatoMSP
        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: crypto-config/peerOrganizations/Stato.eurasia.com/msp
        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.Stato.eurasia.com
              Port: 7051

    - &Repubblicani
        Name: Repubblicani
        ID: RepubblicaniMSP
        MSPDir: crypto-config/peerOrganizations/Repubblicani.eurasia.com/msp
        AnchorPeers:
            - Host: peer0.Repubblicani.eurasia.com
              Port: 7051

    - &Monarchici
        Name: Monarchici
        ID: MonarchiciMSP
        MSPDir: crypto-config/peerOrganizations/Monarchici.eurasia.com/msp
        AnchorPeers:
            - Host: peer0.Monarchici.eurasia.com
              Port: 7051

################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo" and "kafka"
    OrdererType: solo

    Addresses:
        - orderer.eurasia.com:7050

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
            - 127.0.0.1:9092

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:
